service: canary-deployments-test

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - codedeploy:*
      Resource:
        - "*"
plugins:
  - serverless-plugin-aws-alerts
  - serverless-plugin-canary-deployments

custom:
  alerts:
    dashboards: true
  deploymentSettings:
    stages:
      - dev
      - prod

functions:
  hello:
    handler: handler.hello
    events:
      - http: GET hello
      # - stream:
      #     type: dynamodb
      #     arn:
      #       Fn::GetAtt:
      #         - StreamsTestTable
      #         - StreamArn
      - sns: snsTopic
      # - s3: s3canary-samplebucket
    alarms:
      - name: foo
        namespace: 'AWS/Lambda'
        metric: Errors
        threshold: 1
        statistic: Minimum
        period: 60
        evaluationPeriods: 1
        comparisonOperator: GreaterThanOrEqualToThreshold
    deploymentSettings:
      type: Linear10PercentEvery1Minutes
      alias: Live
      preTrafficHook: preHook
      postTrafficHook: postHook
      alarms:
        - HelloFooAlarm
  preHook:
    handler: hooks.pre
  postHook:
    handler: hooks.post

# resources:
#   Resources:
#     StreamsTestTable:
#       Type: AWS::DynamoDB::Table
#       Properties:
#         TableName: StreamsTestTable
#         AttributeDefinitions:
#           - AttributeName: id
#             AttributeType: S
#         KeySchema:
#           - AttributeName: id
#             KeyType: HASH
#         ProvisionedThroughput:
#           ReadCapacityUnits: 1
#           WriteCapacityUnits: 1
#         StreamSpecification:
#           StreamViewType: NEW_AND_OLD_IMAGES
